### ISSUE TITLE
Unable to create /switch solder on SD. No keyfiles written v1.6.2

### ISSUE THREAD

**Issue by Conan179** [shchmue/Lockpick_RCM#12]
Hello, when i using lock_rcm V1.6.2 on my sysnand 8.1.0 switch (no emunand), i becam this error:
Unable to create /switch solder on SD. No keyfiles written

I have a 400gb sandisk mikroSD card.
Older Versions are making nor problems.

Sending the Payload with TegraRcmGUI 2.5

**Comment by shchmue** [comment]
fixed in 340a25651825e4ed3267dbc9f1ab0124a6a882ae

**Comment by Conan179** [comment]
Thanks!

**Comment by robotica72** [comment]
Sorry to bring up this topic after it was closed but using the new version (1.6.3) and I still get the error and it cant dump the keys. (Unable to create /switch folder on SD.  No Keyfiles written.)

Any ideas??

**Comment by shchmue** [comment]
Folks having problems please run this version, the only modification is that it displays the `f_mkdir` error code. Please let me know what codes you're getting.
[Lockpick_RCM.zip](https://github.com/shchmue/Lockpick_RCM/files/3751839/Lockpick_RCM.zip)

**Comment by shchmue** [comment]
that's an unexpected code... anyhow i just went ahead and removed the check altogether, it's unnecessary as i already validate the file write. nothing the program can do about it anyway if it can't create a folder. this matches hekate functionality and it's never had a problem with that.
https://github.com/shchmue/Lockpick_RCM/commit/8c2aa76fd08e61863a3dae27b00c103c5491c4b7

**Comment by shchmue** [comment]
Ahh CTCaer figured it out, I forgot to mount sd card before mkdir call. I'll fix it in the next major release where I improve titlekey dumping speed, should be done soon.

**Comment by robotica72** [comment]
Cool - thanks for the update
